import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import StyleDictionary from "style-dictionary";
import { fileHeader, formattedVariables } from "style-dictionary/utils";
import type { Config, FormatFn, TransformedToken } from "style-dictionary/types";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BUILD_PATH = "src/styles/generated/";

function posixFilePath(token: TransformedToken): string {
  return token.filePath.replaceAll("\\", "/");
}

function isPrimitiveToken(token: TransformedToken): boolean {
  return posixFilePath(token).includes("tokens/primitive/");
}

function isComponentToken(token: TransformedToken): boolean {
  return posixFilePath(token).includes("tokens/component/");
}

function isOpacityToken(token: TransformedToken): boolean {
  return token.path[0] === "opacity";
}

function themeDeclaration(token: TransformedToken): string | null {
  if (isPrimitiveToken(token) || isComponentToken(token) || isOpacityToken(token)) {
    return null;
  }

  const group = token.path[0];
  const rest = token.path.slice(1).join("-");

  if (group === "color") {
    return `--color-${rest}: var(--${token.name});`;
  }
  if (group === "font-size") {
    return `--text-${rest}: var(--${token.name});`;
  }
  if (group === "spacing") {
    return `--spacing-${rest}: var(--${token.name});`;
  }
  if (group === "radius") {
    return `--radius-${rest}: var(--${token.name});`;
  }
  if (group === "border-width") {
    return `--border-width-${rest}: var(--${token.name});`;
  }

  return null;
}

const nameTransform = {
  type: "name" as const,
  transform: (token: TransformedToken) => {
    const kebab = token.path.join("-");
    return isPrimitiveToken(token) ? `primitive-${kebab}` : `ds-${kebab}`;
  },
};

const opacityTransform = {
  type: "value" as const,
  filter: (token: TransformedToken) => isOpacityToken(token),
  transform: (token: TransformedToken, _config: unknown, options: Config) => {
    const raw = options.usesDtcg ? token.$value : token.value;
    if (typeof raw !== "number") {
      throw new Error(`Opacity token ${token.name} is not a number`);
    }
    return Math.round(raw * 100) / 100;
  },
};

const generatedHeader = async () => ["Generated by Style Dictionary from tokens/. Do not edit."];

const cssVariablesFormat: FormatFn = async ({ dictionary, options = {}, file }) => {
  const header = await fileHeader({ file, options });
  const selector = typeof options.selector === "string" ? options.selector : ":root";
  const variables = formattedVariables({
    format: "css",
    dictionary,
    outputReferences: options.outputReferences,
    formatting: { indentation: "  " },
    usesDtcg: options.usesDtcg,
  });

  return `${header}${selector} {\n${variables}\n}\n`;
};

const tailwindThemeFormat: FormatFn = async ({ dictionary, file, options }) => {
  const header = await fileHeader({ file, options });
  const declarations = dictionary.allTokens
    .map(themeDeclaration)
    .filter((line): line is string => line !== null)
    .map((line) => `  ${line}`)
    .join("\n");

  return `${header}@theme inline {\n${declarations}\n}\n`;
};

async function buildCss(config: Config): Promise<void> {
  const sd = new StyleDictionary({
    ...config,
    usesDtcg: true,
    log: {
      warnings: "warn",
      verbosity: "verbose",
      errors: { brokenReferences: "throw" },
    },
  });
  await sd.hasInitialized;
  await sd.buildAllPlatforms();
}

export async function buildTokens(): Promise<void> {
  mkdirSync(join(ROOT, BUILD_PATH), { recursive: true });

  await buildCss({
    include: ["tokens/primitive/**/*.json", "tokens/dimension/**/*.json"],
    source: ["tokens/semantic/light.json", "tokens/component/light.json"],
    hooks: {
      transforms: {
        "name/ds-css": nameTransform,
        "value/opacity-css": opacityTransform,
      },
      formats: {
        "css/ds-variables": cssVariablesFormat,
      },
    },
    platforms: {
      css: {
        transforms: ["name/ds-css", "size/rem", "value/opacity-css"],
        buildPath: BUILD_PATH,
        files: [
          {
            destination: "tokens.css",
            format: "css/ds-variables",
            options: {
              selector: ":root",
              outputReferences: true,
              fileHeader: generatedHeader,
            },
          },
        ],
      },
    },
  });

  await buildCss({
    include: ["tokens/primitive/**/*.json"],
    source: ["tokens/semantic/dark.json"],
    hooks: {
      transforms: {
        "name/ds-css": nameTransform,
        "value/opacity-css": opacityTransform,
      },
      formats: {
        "css/ds-variables": cssVariablesFormat,
      },
    },
    platforms: {
      css: {
        transforms: ["name/ds-css", "size/rem", "value/opacity-css"],
        buildPath: BUILD_PATH,
        files: [
          {
            destination: "tokens.dark.css",
            format: "css/ds-variables",
            filter: (token) => token.isSource,
            options: {
              selector: '[data-theme="dark"]',
              outputReferences: true,
              fileHeader: generatedHeader,
            },
          },
        ],
      },
    },
  });

  await buildCss({
    include: ["tokens/primitive/**/*.json"],
    source: ["tokens/semantic/light.json", "tokens/dimension/**/*.json"],
    hooks: {
      transforms: {
        "name/ds-css": nameTransform,
        "value/opacity-css": opacityTransform,
      },
      formats: {
        "css/tailwind-theme": tailwindThemeFormat,
      },
    },
    platforms: {
      css: {
        transforms: ["name/ds-css", "size/rem", "value/opacity-css"],
        buildPath: BUILD_PATH,
        files: [
          {
            destination: "theme.css",
            format: "css/tailwind-theme",
            filter: (token) => !isPrimitiveToken(token) && !isOpacityToken(token),
            options: {
              fileHeader: generatedHeader,
            },
          },
        ],
      },
    },
  });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await buildTokens();
  console.log(`Wrote generated CSS to ${join(ROOT, BUILD_PATH)}`);
}
